# Shared helpers for the mgcca integration tests. These exercise the INSTALLED
# package against the oracle reference generated by tests/harness/01_oracle.R
# (values dumped under tests/data/reference/<fixture>/<method>/). The per-phase
# sourceCpp harness (tests/harness/03..11) stays as dev tooling -- it recompiles
# the C++ and needs the BDSM build flags, so it is not part of R CMD check.
suppressMessages({
  library(BigDataStatMeth)
})

fixture_path <- function(name) testthat::test_path("..", "data", name)

# Temporary HDF5 files. `h5_tmp()` hands out a path and records it; a file that
# calls `h5_cleanup_on_exit()` has every path it took removed once its tests are
# done, so a build machine is not left carrying them for the rest of its run.
.h5_tmp_reg <- new.env(parent = emptyenv())
.h5_tmp_reg$paths <- character(0)

h5_tmp <- function() {
  p <- tempfile(fileext = ".h5")
  .h5_tmp_reg$paths <- c(.h5_tmp_reg$paths, p)
  p
}

h5_cleanup_on_exit <- function(env = testthat::teardown_env()) {
  withr::defer({
    try(BigDataStatMeth::hdf5_close_all(), silent = TRUE)
    unlink(.h5_tmp_reg$paths, force = TRUE)
    .h5_tmp_reg$paths <- character(0)
  }, envir = env)
}

reference_dir <- function(fixture, method)
  testthat::test_path("..", "data", "reference",
                      sub("\\.rds$", "", fixture), method)

# TRUE when the reference fixtures ship with the source tree (they are excluded
# from the built package, so installed-package checks skip gracefully).
have_reference <- function(fixture, method)
  dir.exists(reference_dir(fixture, method)) &&
  file.exists(fixture_path(fixture))

# Element-wise all.equal, attributes ignored.
eqm <- function(A, B, tol = 1e-5) isTRUE(all.equal(
  unname(as.matrix(A)), unname(as.matrix(B)),
  check.attributes = FALSE, tolerance = tol))

# Column-wise all.equal up to an arbitrary per-column sign (eigenvectors /
# singular vectors have arbitrary sign).
eqs <- function(A, B, tol = 1e-5) {
  A <- unname(as.matrix(A)); B <- unname(as.matrix(B))
  all(dim(A) == dim(B)) && all(vapply(seq_len(ncol(A)), function(k)
    isTRUE(all.equal(A[, k],  B[, k], tolerance = tol)) ||
    isTRUE(all.equal(A[, k], -B[, k], tolerance = tol)), logical(1)))
}

# Run mgcca on a fixture into a fresh temp HDF5 file. Returns the result
# list plus a reader closure `read(path)` over the output file.
run_fixture <- function(fixture, method, lambda = NULL, ..., scores = TRUE) {
  tabs <- readRDS(fixture_path(fixture))
  h5   <- tempfile(fileext = ".h5")
  res  <- mgcca(tabs, filename = h5, nfac = 2, method = method,
                lambda = lambda, scores = scores, collect = FALSE, ...)
  list(res = res, h5 = h5,
       read = function(path) as.matrix(hdf5_matrix(h5, path)))
}
