# End-to-end parity of mgcca() (penalized) with the R oracle. Scaling now
# happens in-HDF5 inside mgcca_rcpp; the reference was generated by the oracle
# with base-R scale(), so a match here also validates the in-HDF5 normalization.

test_that("mgcca (penalized) matches the R oracle end-to-end", {
  skip_if_not(have_reference("mgcca_subset.rds", "penalized"),
              "reference fixtures not shipped with the built package")

  o   <- run_fixture("mgcca_subset.rds", "penalized", lambda = c(0.75, 1))
  REF <- reference_dir("mgcca_subset.rds", "penalized")
  rd  <- function(n) readRDS(file.path(REF, paste0(n, ".rds")))
  on.exit(BigDataStatMeth::hdf5_close_all(), add = TRUE)

  expect_equal(o$res$m, 80L)
  expect_true(eqs(o$read("FINAL_RESULTS/Y"), rd("Y")))
  expect_true(eqm(as.vector(o$read("FINAL_RESULTS/AVE/AVE_inner")),
                  rd("AVE_inner")))
  for (i in seq_along(o$res$datasets)) {
    ds <- o$res$datasets[i]
    # corsY = cor(X, Y) inherits Y's arbitrary per-column eigenvector sign, so it
    # is sign-tolerant like Y/scores (a direct vs iterative eigensolver may flip it).
    expect_true(eqs(o$read(paste0("FINAL_RESULTS/corsY/", ds)),
                    rd(sprintf("t%d_corsY", i))), info = ds)
    expect_true(eqs(o$read(paste0("FINAL_RESULTS/scores/", ds)),
                    rd(sprintf("t%d_scores", i))), info = ds)
  }
})
