// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_AVE
Rcpp::List get_AVE(const std::string& filename, const std::string& group, const std::vector<std::string>& datasets, const int nfac, std::vector<int>& p, Rcpp::Nullable<int> wsize);
RcppExport SEXP _mgcca_get_AVE(SEXP filenameSEXP, SEXP groupSEXP, SEXP datasetsSEXP, SEXP nfacSEXP, SEXP pSEXP, SEXP wsizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type datasets(datasetsSEXP);
    Rcpp::traits::input_parameter< const int >::type nfac(nfacSEXP);
    Rcpp::traits::input_parameter< std::vector<int>& >::type p(pSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type wsize(wsizeSEXP);
    rcpp_result_gen = Rcpp::wrap(get_AVE(filename, group, datasets, nfac, p, wsize));
    return rcpp_result_gen;
END_RCPP
}
// mgcca_rcpp
void mgcca_rcpp(std::string filename, std::string group, std::vector<std::string> datasets, int nfac, int scale, int pval, int scores, std::string method, Rcpp::Nullable<std::vector<double>> lambda, Rcpp::Nullable<int> mccores);
RcppExport SEXP _mgcca_mgcca_rcpp(SEXP filenameSEXP, SEXP groupSEXP, SEXP datasetsSEXP, SEXP nfacSEXP, SEXP scaleSEXP, SEXP pvalSEXP, SEXP scoresSEXP, SEXP methodSEXP, SEXP lambdaSEXP, SEXP mccoresSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type group(groupSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type datasets(datasetsSEXP);
    Rcpp::traits::input_parameter< int >::type nfac(nfacSEXP);
    Rcpp::traits::input_parameter< int >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< int >::type pval(pvalSEXP);
    Rcpp::traits::input_parameter< int >::type scores(scoresSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<std::vector<double>> >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type mccores(mccoresSEXP);
    mgcca_rcpp(filename, group, datasets, nfac, scale, pval, scores, method, lambda, mccores);
    return R_NilValue;
END_RCPP
}

RcppExport SEXP block_cgls(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP block_cgls_sparse(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP cgls(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP cgls_sparse(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP geninv(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_mgcca_get_AVE", (DL_FUNC) &_mgcca_get_AVE, 6},
    {"_mgcca_mgcca_rcpp", (DL_FUNC) &_mgcca_mgcca_rcpp, 10},
    {"block_cgls",        (DL_FUNC) &block_cgls,        6},
    {"block_cgls_sparse", (DL_FUNC) &block_cgls_sparse, 6},
    {"cgls",              (DL_FUNC) &cgls,              6},
    {"cgls_sparse",       (DL_FUNC) &cgls_sparse,       6},
    {"geninv",            (DL_FUNC) &geninv,            1},
    {NULL, NULL, 0}
};

RcppExport void R_init_mgcca(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
