// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mgcca_XKX_rcpp
Rcpp::List mgcca_XKX_rcpp(std::string filename, std::string tmp_group, std::vector<std::string> datasets, int inv_method, Rcpp::Nullable<std::vector<double>> lambda, Rcpp::Nullable<int> threads);
RcppExport SEXP _mgcca_mgcca_XKX_rcpp(SEXP filenameSEXP, SEXP tmp_groupSEXP, SEXP datasetsSEXP, SEXP inv_methodSEXP, SEXP lambdaSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type tmp_group(tmp_groupSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type datasets(datasetsSEXP);
    Rcpp::traits::input_parameter< int >::type inv_method(inv_methodSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<std::vector<double>> >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcca_XKX_rcpp(filename, tmp_group, datasets, inv_method, lambda, threads));
    return rcpp_result_gen;
END_RCPP
}
// mgcca_write_attrs_rcpp
void mgcca_write_attrs_rcpp(std::string filename, std::string group, std::string dataset, Rcpp::List attrs);
RcppExport SEXP _mgcca_mgcca_write_attrs_rcpp(SEXP filenameSEXP, SEXP groupSEXP, SEXP datasetSEXP, SEXP attrsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type group(groupSEXP);
    Rcpp::traits::input_parameter< std::string >::type dataset(datasetSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type attrs(attrsSEXP);
    mgcca_write_attrs_rcpp(filename, group, dataset, attrs);
    return R_NilValue;
END_RCPP
}
// mgcca_read_attrs_rcpp
Rcpp::List mgcca_read_attrs_rcpp(std::string filename, std::string group, std::string dataset);
RcppExport SEXP _mgcca_mgcca_read_attrs_rcpp(SEXP filenameSEXP, SEXP groupSEXP, SEXP datasetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type group(groupSEXP);
    Rcpp::traits::input_parameter< std::string >::type dataset(datasetSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcca_read_attrs_rcpp(filename, group, dataset));
    return rcpp_result_gen;
END_RCPP
}
// mgcca_list_group_rcpp
Rcpp::CharacterVector mgcca_list_group_rcpp(std::string filename, std::string group);
RcppExport SEXP _mgcca_mgcca_list_group_rcpp(SEXP filenameSEXP, SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type group(groupSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcca_list_group_rcpp(filename, group));
    return rcpp_result_gen;
END_RCPP
}
// mgcca_cor_ave_rcpp
Rcpp::List mgcca_cor_ave_rcpp(std::string filename, std::string tmp_group, std::vector<std::string> datasets, int nfac, std::string final_group);
RcppExport SEXP _mgcca_mgcca_cor_ave_rcpp(SEXP filenameSEXP, SEXP tmp_groupSEXP, SEXP datasetsSEXP, SEXP nfacSEXP, SEXP final_groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type tmp_group(tmp_groupSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type datasets(datasetsSEXP);
    Rcpp::traits::input_parameter< int >::type nfac(nfacSEXP);
    Rcpp::traits::input_parameter< std::string >::type final_group(final_groupSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcca_cor_ave_rcpp(filename, tmp_group, datasets, nfac, final_group));
    return rcpp_result_gen;
END_RCPP
}
// mgcca_eigen_rcpp
Rcpp::List mgcca_eigen_rcpp(std::string filename, std::string tmp_group, std::vector<std::string> datasets, int nfac, std::string final_group, Rcpp::Nullable<int> threads);
RcppExport SEXP _mgcca_mgcca_eigen_rcpp(SEXP filenameSEXP, SEXP tmp_groupSEXP, SEXP datasetsSEXP, SEXP nfacSEXP, SEXP final_groupSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type tmp_group(tmp_groupSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type datasets(datasetsSEXP);
    Rcpp::traits::input_parameter< int >::type nfac(nfacSEXP);
    Rcpp::traits::input_parameter< std::string >::type final_group(final_groupSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcca_eigen_rcpp(filename, tmp_group, datasets, nfac, final_group, threads));
    return rcpp_result_gen;
END_RCPP
}
// mgcca_getK_rcpp
Rcpp::List mgcca_getK_rcpp(std::string filename, std::string in_group, std::vector<std::string> datasets, std::string out_group);
RcppExport SEXP _mgcca_mgcca_getK_rcpp(SEXP filenameSEXP, SEXP in_groupSEXP, SEXP datasetsSEXP, SEXP out_groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type in_group(in_groupSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type datasets(datasetsSEXP);
    Rcpp::traits::input_parameter< std::string >::type out_group(out_groupSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcca_getK_rcpp(filename, in_group, datasets, out_group));
    return rcpp_result_gen;
END_RCPP
}
// mgcca_rcpp
Rcpp::List mgcca_rcpp(std::string filename, std::string in_group, std::vector<std::string> datasets, int nfac, int inv_method, Rcpp::Nullable<std::vector<double>> lambda, bool scores, bool scale, std::string route, std::string tmp_group, std::string final_group, Rcpp::Nullable<int> threads);
RcppExport SEXP _mgcca_mgcca_rcpp(SEXP filenameSEXP, SEXP in_groupSEXP, SEXP datasetsSEXP, SEXP nfacSEXP, SEXP inv_methodSEXP, SEXP lambdaSEXP, SEXP scoresSEXP, SEXP scaleSEXP, SEXP routeSEXP, SEXP tmp_groupSEXP, SEXP final_groupSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type in_group(in_groupSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type datasets(datasetsSEXP);
    Rcpp::traits::input_parameter< int >::type nfac(nfacSEXP);
    Rcpp::traits::input_parameter< int >::type inv_method(inv_methodSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<std::vector<double>> >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type scores(scoresSEXP);
    Rcpp::traits::input_parameter< bool >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< std::string >::type route(routeSEXP);
    Rcpp::traits::input_parameter< std::string >::type tmp_group(tmp_groupSEXP);
    Rcpp::traits::input_parameter< std::string >::type final_group(final_groupSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcca_rcpp(filename, in_group, datasets, nfac, inv_method, lambda, scores, scale, route, tmp_group, final_group, threads));
    return rcpp_result_gen;
END_RCPP
}
// mgcca_scores_rcpp
Rcpp::List mgcca_scores_rcpp(std::string filename, std::string tmp_group, std::vector<std::string> datasets, int nfac, std::string final_group);
RcppExport SEXP _mgcca_mgcca_scores_rcpp(SEXP filenameSEXP, SEXP tmp_groupSEXP, SEXP datasetsSEXP, SEXP nfacSEXP, SEXP final_groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type tmp_group(tmp_groupSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type datasets(datasetsSEXP);
    Rcpp::traits::input_parameter< int >::type nfac(nfacSEXP);
    Rcpp::traits::input_parameter< std::string >::type final_group(final_groupSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcca_scores_rcpp(filename, tmp_group, datasets, nfac, final_group));
    return rcpp_result_gen;
END_RCPP
}
// mgcca_scores_svd_rcpp
Rcpp::List mgcca_scores_svd_rcpp(std::string filename, std::string tmp_group, std::vector<std::string> datasets, int inv_method, int nfac, Rcpp::Nullable<std::vector<double>> lambda, std::string final_group);
RcppExport SEXP _mgcca_mgcca_scores_svd_rcpp(SEXP filenameSEXP, SEXP tmp_groupSEXP, SEXP datasetsSEXP, SEXP inv_methodSEXP, SEXP nfacSEXP, SEXP lambdaSEXP, SEXP final_groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type tmp_group(tmp_groupSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type datasets(datasetsSEXP);
    Rcpp::traits::input_parameter< int >::type inv_method(inv_methodSEXP);
    Rcpp::traits::input_parameter< int >::type nfac(nfacSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<std::vector<double>> >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< std::string >::type final_group(final_groupSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcca_scores_svd_rcpp(filename, tmp_group, datasets, inv_method, nfac, lambda, final_group));
    return rcpp_result_gen;
END_RCPP
}
// mgcca_svd_rcpp
Rcpp::List mgcca_svd_rcpp(std::string filename, std::string tmp_group, std::vector<std::string> datasets, int inv_method, Rcpp::Nullable<std::vector<double>> lambda, std::string svd_method, Rcpp::Nullable<int> threads);
RcppExport SEXP _mgcca_mgcca_svd_rcpp(SEXP filenameSEXP, SEXP tmp_groupSEXP, SEXP datasetsSEXP, SEXP inv_methodSEXP, SEXP lambdaSEXP, SEXP svd_methodSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type tmp_group(tmp_groupSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type datasets(datasetsSEXP);
    Rcpp::traits::input_parameter< int >::type inv_method(inv_methodSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<std::vector<double>> >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< std::string >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(mgcca_svd_rcpp(filename, tmp_group, datasets, inv_method, lambda, svd_method, threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mgcca_mgcca_XKX_rcpp", (DL_FUNC) &_mgcca_mgcca_XKX_rcpp, 6},
    {"_mgcca_mgcca_write_attrs_rcpp", (DL_FUNC) &_mgcca_mgcca_write_attrs_rcpp, 4},
    {"_mgcca_mgcca_read_attrs_rcpp", (DL_FUNC) &_mgcca_mgcca_read_attrs_rcpp, 3},
    {"_mgcca_mgcca_list_group_rcpp", (DL_FUNC) &_mgcca_mgcca_list_group_rcpp, 2},
    {"_mgcca_mgcca_cor_ave_rcpp", (DL_FUNC) &_mgcca_mgcca_cor_ave_rcpp, 5},
    {"_mgcca_mgcca_eigen_rcpp", (DL_FUNC) &_mgcca_mgcca_eigen_rcpp, 6},
    {"_mgcca_mgcca_getK_rcpp", (DL_FUNC) &_mgcca_mgcca_getK_rcpp, 4},
    {"_mgcca_mgcca_rcpp", (DL_FUNC) &_mgcca_mgcca_rcpp, 12},
    {"_mgcca_mgcca_scores_rcpp", (DL_FUNC) &_mgcca_mgcca_scores_rcpp, 5},
    {"_mgcca_mgcca_scores_svd_rcpp", (DL_FUNC) &_mgcca_mgcca_scores_svd_rcpp, 7},
    {"_mgcca_mgcca_svd_rcpp", (DL_FUNC) &_mgcca_mgcca_svd_rcpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_mgcca(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
