#' Simulated cardiovascular multi-table example data
#'
#' @description A small, self-contained example for \code{\link{mgcca}}: three
#'   simulated tables measured on partly overlapping sets of individuals,
#'   illustrating the missing-individuals setting mgcca is designed for.
#'   Loading the data set creates three data frames, \code{X1}, \code{X2} and
#'   \code{X3}, in the calling environment.
#'
#'   The data are simulated. They are drawn from aggregate summary statistics
#'   of a real cardiovascular methylation study (see \emph{Source}) and mimic
#'   its correlation and missingness structure, but no individual in the data
#'   set corresponds to a real participant. The tables are meant for
#'   illustration and testing only; they support no substantive conclusion
#'   about methylation, cardiovascular risk or blood composition.
#'
#' @details Each table has individuals in rows -- identified by synthetic
#'   identifiers \code{id0001}--\code{id0646} shared across tables -- and
#'   variables in columns; every column is numeric and there are no missing
#'   values within a table. The three tables do not share exactly the same
#'   individuals: the union is 646 individuals and only 606 are common to all
#'   three, which is the incomplete-blocks situation \code{\link{mgcca}}
#'   handles:
#'   \describe{
#'     \item{\code{X1}}{618 x 69 data frame of simulated standardized
#'       methylation-derived scores (columns \code{cg1}--\code{cg69}), each
#'       centred and scaled.}
#'     \item{\code{X2}}{633 x 6 data frame of simulated clinical measurements:
#'       \code{TC} (total cholesterol), \code{LDL}, \code{HDL}, \code{BMI},
#'       \code{waist} (waist circumference) and \code{Gluc} (glucose).}
#'     \item{\code{X3}}{645 x 4 data frame of simulated blood cell-type
#'       proportion estimates: \code{CD4T}, \code{NK}, \code{Mono} and
#'       \code{Gran}. These are four components of a six-type composition; the
#'       remaining two were set aside, so the four columns do not sum to one by
#'       construction.}
#'   }
#'
#'   \code{\link{mgcca}} expects numeric matrices, so coerce the tables with
#'   \code{as.matrix()} before fitting (see the examples).
#'
#' @format Three numeric data frames with individuals in rows and variables in
#'   columns:
#'   \describe{
#'     \item{\code{X1}}{\code{data.frame} with 618 rows and 69 columns
#'       (simulated methylation-derived scores).}
#'     \item{\code{X2}}{\code{data.frame} with 633 rows and 6 columns
#'       (simulated clinical measurements).}
#'     \item{\code{X3}}{\code{data.frame} with 645 rows and 4 columns
#'       (simulated cell-type proportions).}
#'   }
#' @source Simulated data, generated by the script
#'   \code{system.file("scripts", "make-cardiovascular.R", package = "mgcca")}
#'   from aggregate summary statistics -- a joint correlation matrix,
#'   per-variable marginal distributions and the sizes of the missing-value
#'   pattern -- of a real, de-identified cardiovascular methylation study that
#'   cannot be redistributed. Those aggregates are stored alongside the script
#'   in \code{cardiovascular-parameters.rds}; no individual-level information
#'   from the source study is retained in the package.
#' @name cardiovascular
#' @aliases cardiovascular X1 X2 X3
#' @docType data
#' @keywords datasets
#' @usage data(cardiovascular)
#' @examples
#' data(cardiovascular)
#' X <- list(methylation = as.matrix(X1),
#'           clinical    = as.matrix(X2),
#'           other       = as.matrix(X3))
#' vapply(X, dim, integer(2))
NULL
