# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' MGCCA XKX stage (Mgram=X'X, inverse, Mi=X xkx X') over HDF5
#' @keywords internal
mgcca_XKX_rcpp <- function(filename, tmp_group, datasets, inv_method, lambda = NULL, threads = NULL) {
    .Call('_mgcca_mgcca_XKX_rcpp', PACKAGE = 'mgcca', filename, tmp_group, datasets, inv_method, lambda, threads)
}

#' Write HDF5 attributes to a dataset or group
#'
#' Writes each named element of \code{attrs} as an HDF5 attribute. When
#' \code{dataset} is the empty string the attributes are attached to the group
#' \code{group}; otherwise they are attached to the dataset \code{group/dataset}.
#' Supports scalar and vector character/integer/double/logical values (logical
#' is stored as integer 0/1, since HDF5 has no native boolean).
#'
#' @param filename Path to the HDF5 file.
#' @param group Group path (target group, or the parent group of the dataset).
#' @param dataset Dataset name, or "" to target the group itself.
#' @param attrs Named list of attribute values.
#' @keywords internal
mgcca_write_attrs_rcpp <- function(filename, group, dataset, attrs) {
    invisible(.Call('_mgcca_mgcca_write_attrs_rcpp', PACKAGE = 'mgcca', filename, group, dataset, attrs))
}

#' Read all HDF5 attributes from a dataset or group
#'
#' Returns every attribute (except BigDataStatMeth's internal bookkeeping
#' attribute) as a named list. When \code{dataset} is the empty string the
#' attributes are read from the group \code{group}; otherwise from the dataset
#' \code{group/dataset}.
#'
#' @param filename Path to the HDF5 file.
#' @param group Group path (source group, or the parent group of the dataset).
#' @param dataset Dataset name, or "" to read from the group itself.
#' @return Named list of attribute values.
#' @keywords internal
mgcca_read_attrs_rcpp <- function(filename, group, dataset) {
    .Call('_mgcca_mgcca_read_attrs_rcpp', PACKAGE = 'mgcca', filename, group, dataset)
}

#' List the immediate children of an HDF5 group
#'
#' Returns the names of the objects (datasets and subgroups) directly under
#' \code{group}, without depending on the rhdf5 package. Used by
#' \code{mgcca_load} to auto-discover table names in files written before the
#' provenance manifest existed.
#'
#' @param filename Path to the HDF5 file.
#' @param group Group whose children to list.
#' @return Character vector of child object names.
#' @keywords internal
mgcca_list_group_rcpp <- function(filename, group) {
    .Call('_mgcca_mgcca_list_group_rcpp', PACKAGE = 'mgcca', filename, group)
}

#' MGCCA corsY / p-values / AVE stage over HDF5
#' @keywords internal
mgcca_cor_ave_rcpp <- function(filename, tmp_group, datasets, nfac, final_group = "FINAL_RESULTS") {
    .Call('_mgcca_mgcca_cor_ave_rcpp', PACKAGE = 'mgcca', filename, tmp_group, datasets, nfac, final_group)
}

#' MGCCA eigen stage (Ksum, MKsum05, eigen, Y) over HDF5
#' @keywords internal
mgcca_eigen_rcpp <- function(filename, tmp_group, datasets, nfac, final_group = "FINAL_RESULTS", threads = NULL) {
    .Call('_mgcca_mgcca_eigen_rcpp', PACKAGE = 'mgcca', filename, tmp_group, datasets, nfac, final_group, threads)
}

#' MGCCA getK stage (build padded X and indicator diagonal K) over HDF5
#' @keywords internal
mgcca_getK_rcpp <- function(filename, in_group, datasets, out_group = "MGCCA_TMP") {
    .Call('_mgcca_mgcca_getK_rcpp', PACKAGE = 'mgcca', filename, in_group, datasets, out_group)
}

#' MGCCA over HDF5 (single-call C++ orchestrator)
#'
#' @param filename HDF5 file with input tables already written under \code{in_group}.
#' @param in_group Input group (default \code{"MGCCA_IN"}).
#' @param datasets Character vector of dataset names inside \code{in_group}.
#' @param nfac Number of shared components.
#' @param inv_method 1 = solve (SPD Cholesky), 2 = penalized (+lambda I),
#'   3 = geninv/ginv (pseudoinverse).
#' @param lambda Numeric vector (length = #tables) for \code{inv_method = 2}.
#' @param scores If TRUE, also compute per-table weights and scores.
#' @param scale If TRUE (default), column-center+scale each table in-HDF5
#'   (out-of-core, base-R \code{scale()} semantics) before the analysis, reading
#'   the raw tables from \code{in_group} and never loading them fully into RAM.
#' @param route Per-table algebra route: \code{"auto"} (default) picks per table
#'   by \code{min(n, p)} -- covariance \code{X'X} (p x p) when \code{p < n},
#'   Gram \code{XX'} (n x n) when \code{p >= n}; \code{"cov"} forces the
#'   covariance route for all tables; \code{"dual"} forces the Gram route.
#' @param tmp_group Group for intermediates (default \code{"MGCCA_TMP"}).
#' @param final_group Group for results (default \code{"FINAL_RESULTS"}).
#' @param threads Optional thread count.
#' @return A descriptor list (filename, datasets, nfac, m, eigenvalues, route,
#'   route_dual, final_group). Results are written under \code{final_group}.
#' @seealso \code{\link{mgcca}}, \code{\link{mgcca_results}}
#' @export
mgcca_rcpp <- function(filename, in_group, datasets, nfac, inv_method, lambda = NULL, scores = FALSE, scale = TRUE, route = "auto", tmp_group = "MGCCA_TMP", final_group = "FINAL_RESULTS", threads = NULL) {
    .Call('_mgcca_mgcca_rcpp', PACKAGE = 'mgcca', filename, in_group, datasets, nfac, inv_method, lambda, scores, scale, route, tmp_group, final_group, threads)
}

#' MGCCA scores stage (A=B_j, weights, scores) over HDF5
#' @keywords internal
mgcca_scores_rcpp <- function(filename, tmp_group, datasets, nfac, final_group = "FINAL_RESULTS") {
    .Call('_mgcca_mgcca_scores_rcpp', PACKAGE = 'mgcca', filename, tmp_group, datasets, nfac, final_group)
}

#' MGCCA dual scores stage (A=V diag(w_A) U'Y, weights, scores) over HDF5
#' @keywords internal
mgcca_scores_svd_rcpp <- function(filename, tmp_group, datasets, inv_method, nfac, lambda = NULL, final_group = "FINAL_RESULTS") {
    .Call('_mgcca_mgcca_scores_svd_rcpp', PACKAGE = 'mgcca', filename, tmp_group, datasets, inv_method, nfac, lambda, final_group)
}

#' MGCCA dual SVD stage: M_j = U diag(w) U' from SVD(X_j)
#' @keywords internal
mgcca_svd_rcpp <- function(filename, tmp_group, datasets, inv_method, lambda = NULL, svd_method = "full", threads = NULL) {
    .Call('_mgcca_mgcca_svd_rcpp', PACKAGE = 'mgcca', filename, tmp_group, datasets, inv_method, lambda, svd_method, threads)
}

